version: '3.9'

services:
  database:
      build: .
      volumes:
        - pgdata:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=username
        - POSTGRES_PASSWORD=secret
        - POSTGRES_DB=fifa
      ports:
        - 5432:5432
      restart: always
      networks:
        - project_network
      
  adminer:
      image: adminer
      restart: always
      depends_on:
        - database
      ports:
        - 8080:8080
      networks:
        - project_network

  streamlit:
      build: ./app/streamlit
      depends_on:
        - database
      ports:
        - 8501:8501
      volumes:
      - streamvol:/app/  
      networks:
        - project_network      

volumes:
  pgdata:
  streamvol:
networks:
    project_network:
      name: project_network
      driver: bridge
